service: sl-order-gateway
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  environment:
    SERVICE_NAME: ${self:service}
    sqs_event: ${self:custom.globals.sqs.order}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"    
# you can add packaging information here
package:
  individually: true

functions:
  ${file(src/index.yml)}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

custom:
  globals:
    role: ${self:service}-${self:provider.stage}-role
    sqs:
      order: ${self:service}-order-${self:provider.stage}

resources:
  ${file(resources/resources.yml)}

